spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  password:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

exchange:
  rate:
    lookup:
      period:
        months: 6