name: Run Tests And Save Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Run tests
        run: mvn verify
      - name: Staging
        run: mkdir staging && cp target/*.jar staging
      - name: Upload as package
        uses: actions/upload-artifact@v4
        with:
          name: TransactionConverter
          path: staging
